siapi_indexer:
    resource: "@SiapiIndexerBundle/Resources/config/routing.xml"
    prefix:   /

siapi_search:
    resource: "@SiapiSearchBundle/Resources/config/routing.xml"
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
