<?php

namespace Siapi\IndexerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Siapi\IndexerBundle\Entity\IndexerLog;

/**
 * IndexerLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndexerLogRepository extends EntityRepository
{

    /**
     * @param string $id
     * @return \Siapi\IndexerBundle\Entity\IndexerLog|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByRemoteId($id)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('il')
            ->from('\Siapi\IndexerBundle\Entity\IndexerLog', 'il')
            ->where('il.id = :identifier')
            ->setParameter('identifier', $id);

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * @param int $start
     * @param int $end
     * @param string $format
     */
    public function createRange($start, $end, $format)
    {

        for ($i = $start; $i <= $end; $i++) {

            $remoteId = sprintf($format, $i);
            $log = $this->getByRemoteId($remoteId);

            if (is_null($log)) {
                $log = new IndexerLog();
                $log->setRemoteId($remoteId);
                $this->_em->persist($log);
            }
        }

        $this->_em->flush();
    }
}
